resources:
  containers:
  - container: custom
    image: ghcr.io/cronjevh/azure-devops-runner:0.0.11

container: custom

trigger:
- master

pool: 'Azure Pipelines'

steps:

- script: |
    echo Seeing if Docker is available
    docker ps
    k3d cluster create
    kubectl get pods --all-namespaces
    # flux bootstrap git \
    # --url "https://github.com/cronjevh/gitops-sandbox" \
    # --components-extra=image-reflector-controller,image-automation-controller \
    # --branch $BRANCH \
    # --token-auth \
    # --password ${GITHUB_TOKEN} \
    # --path "/deploy/bootstrap"
  displayName: 'Run a multi-line script'
