resources:
  containers:
  - container: custom
    image: ghcr.io/cronjevh/azure-devops-runner:0.0.5

container: custom

trigger:
- master

pool: 'Azure Pipelines'

steps:

- script: |
    echo Seeing if Docker is available
    docker ps
  displayName: 'Run a multi-line script'
