---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: azure-devop-runner
  namespace: flux-system
spec:
  image: ghcr.io/cronjevh/azure-devops-runner
  interval: 1m0s

