apiVersion: ENC[AES256_GCM,data:2xk=,iv:Kqw2/nQqVR6um6o8g2xbdHsgRgDkReElNrmrirpT7xg=,tag:zwGg4wX8KlrtiiAuFHT8Aw==,type:str]
kind: ENC[AES256_GCM,data:yC6+nBIG,iv:H9uMojWR2x4Uxl4XJr463zYsICoBWAuUDPUEZYIO0O4=,tag:BUmNz1W4HibbPEcN8sm4jg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jW2W+TH9XcoJGVMz9ZRv6Q==,iv:IhKh418bf3jw8Uh/jUq+rbg7RBZl9UmKsacWkkLXwiQ=,tag:WHbKLSo7YRzJ/bHovOvHrQ==,type:str]
    namespace: ENC[AES256_GCM,data:d6r6SrCs5xgYSbVFboEJO4MrGA==,iv:LwllSatRlnp8p1ku3SUCHqpMJwMVEYl167iP12EGvi4=,tag:MQZefIXYT8fFlYt0vkjyOw==,type:str]
type: ENC[AES256_GCM,data:HvfkT8vX,iv:xG9l/4BpfpPwk8W5S2otRePD/qgVLKXH3BA1tp6E59w=,tag:M8H4SxIhsxsR7H6wAZZMhA==,type:str]
data:
    pat: ENC[AES256_GCM,data:xY2HENuQWWjvgquJ+naMHWcIiFw7IAFjwCYUYEzhNIxyJto1aGXQEdWFlR/XMWKeikOZA3tW+Kt1TMqrN3kVlQRVU7Bl4Q==,iv:YolCNqOJ1HGXQ47NUrlprP6FxNzDVyDVwxhUZ/LNKto=,tag:zmV+e3vZgx8il6Hjqcm45Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://cronjevh.vault.azure.net
          name: sops-key
          version: 84bb6aa88e0c411693ed053d696645de
          created_at: "2022-06-19T14:54:39Z"
          enc: OO5zqHrmcSBTlsx3UUNH7Dr0lyKkH9CIeyGOoW-zW_8Bp1uz07E7ktliXrjKm318stgCgpB3KIT1V6vqD_SEdFn7uCrSscU5huQEH5iE0R1jMNzf0voUwufXk5gs6Qo5fDlP6wkvXDHjmPA2ea5tKJRRj9PC9gLUfO8-es_90Kp9huqHdt2CzdNLh0hwVA6OOXBaCJsfKKKP1H3GEy0nUlAZDMNUco7lsQ3N7DLWNL8DJR-j0aiHS8p8ylKqfnfuilmLipJZgD8mz8Ile4HHpYwwcFvA48ho9NgcHaHDgDM92e6rPX__fyRAefLMeXvXLhA28jRRNuM4bx72824Tdg
    hc_vault: []
    age: []
    lastmodified: "2022-06-19T14:54:52Z"
    mac: ENC[AES256_GCM,data:w05F2HzXKQsUwkAU1I8NSTyQtTFYbqKhgknVeu372HkphrSFDhST7bWhgC3rKQrY+yr0wytfpRggpa7gY6ckP3RS098oeU95zntQmwif8Ul3/UAEo3/gZAJ28Jao6oC0PBABhVm9JL/9PwLlEKnPIOtoRVGjEDVHOZr/R4FBzNk=,iv:0/gjwPYqDImjkekBpGAC0FBzEb0Wm9hcr1kL7H3Xngs=,tag:vURXxjY5nP8K733oYqTP1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
