apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-devops-runner
  namespace: azure-devops-runner
spec:
  releaseName: azure-devops-runner
  chart:
    spec:
      chart: azure-pipelines-agent
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    pipelines:
      url: "https://dev.azure.com/cronjevh"
      pat:
        secretRef:
          name: azure-devops-pat
          key: pat
      agent:
        mountDocker: false
    image:
      repository: ghcr.io/cronjevh/azure-devops-runner
      pullPolicy: IfNotPresent
      tag: "0.0.3" # {"$imagepolicy": "flux-system:azure-devops-runner:tag"}
    extraVolumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    extraVolumeMounts:
    - name: dockersock
      mountPath: "/var/run/docker.sock"
    serviceAccount:
      clusterAdmin: true
