apiVersion: v1
kind: Namespace
metadata:
  name: logging

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: v1
kind: Namespace
metadata:
  name: heartbeat

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: imdb
  name: imdb

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: podinfo
  name: podinfo

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: nginx
  name: nginx

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: redis
  name: redis
